use sea_orm::{
    ConnectionTrait, EntityTrait, QueryFilter, QuerySelect, TransactionSession, TransactionTrait,
};

use crate::{ApiError, CRUDResource, PrimaryKeyType};

/// Controls query filtering and field visibility for scoped (e.g., public) requests.
///
/// Inject via Axum `Extension` in middleware. When present:
/// - `get_all_handler` merges `condition` into the query filter
/// - `get_one_handler` verifies the fetched record passes the condition
/// - Write handlers check existing and resulting rows in one transaction
/// - If scoped models exist (`exclude(scoped)` on fields), handlers return the scoped
///   model type which omits those fields from the response
///
/// Auth-system-agnostic: write middleware that converts your auth state into this.
///
/// # Example
///
/// ```rust,ignore
/// use crudcrate::ScopeCondition;
/// use sea_orm::Condition;
///
/// // Middleware: inject scope for unauthenticated users
/// if !is_admin(&req) {
///     req.extensions_mut().insert(ScopeCondition::new(
///         Condition::all().add(article::Column::IsPrivate.eq(false))
///     ));
/// }
/// ```
#[derive(Clone)]
pub struct ScopeCondition {
    pub condition: sea_orm::Condition,
}

impl ScopeCondition {
    /// Create a scope with a query condition (row filtering).
    #[must_use]
    pub fn new(condition: sea_orm::Condition) -> Self {
        Self { condition }
    }
}

/// Trait for types that can be filtered in scoped (public) contexts.
///
/// Types with `exclude(scoped)` boolean fields auto-implement this to return `false`
/// when the record should be hidden from scoped responses. The derive macro generates
/// the impl based on `exclude(scoped)` boolean fields.
///
/// Used by scoped `From` conversions to filter private children out of Vec and Option join fields.
pub trait ScopeFilterable {
    /// Returns `true` if this record should be visible in scoped (public) responses.
    fn is_scope_visible(&self) -> bool {
        true
    }

    /// Returns a Sea-ORM `Condition` that filters this entity's rows to only scope-visible ones.
    ///
    /// Auto-generated by the derive macro from `exclude(scoped)` boolean fields.
    /// For example, an entity with `#[crudcrate(exclude(scoped))] pub is_private: bool`
    /// generates: `Some(Condition::all().add(Column::IsPrivate.eq(false)))`.
    ///
    /// Returns `None` if the entity has no scope-relevant fields (all rows visible).
    ///
    /// Used by join loading to filter child entities at the SQL level during scoped requests,
    /// avoiding loading private children into memory.
    #[must_use]
    fn scope_condition() -> Option<sea_orm::Condition> {
        None
    }
}

async fn contains<R: CRUDResource, C: ConnectionTrait>(
    db: &C,
    id: PrimaryKeyType<R>,
    scope: &ScopeCondition,
    lock: bool,
) -> Result<bool, ApiError> {
    let query = R::EntityType::find_by_id(id).filter(scope.condition.clone());
    let query = if lock { query.lock_exclusive() } else { query };
    Ok(query.one(db).await?.is_some())
}

async fn check_existing<R: CRUDResource, C: ConnectionTrait>(
    db: &C,
    ids: &[PrimaryKeyType<R>],
    scope: &ScopeCondition,
) -> Result<(), ApiError> {
    for id in ids {
        if !contains::<R, _>(db, id.clone(), scope, true).await? {
            return Err(ApiError::not_found(
                R::RESOURCE_NAME_SINGULAR,
                Some(id.to_string()),
            ));
        }
    }
    Ok(())
}

async fn check_result<R: CRUDResource, C: ConnectionTrait>(
    db: &C,
    rows: &[R],
    scope: &ScopeCondition,
) -> Result<(), ApiError> {
    for row in rows {
        if !contains::<R, _>(db, row.resource_id()?, scope, false).await? {
            return Err(ApiError::forbidden("Write would leave the permitted scope"));
        }
    }
    Ok(())
}

/// Run `create` with optional row confinement, preserving the resource's hooks.
///
/// # Errors
/// Returns the operation error, or refuses a row outside the scope.
pub async fn create<R: CRUDResource, C: ConnectionTrait + TransactionTrait>(
    db: &C,
    data: R::CreateModel,
    scope: Option<&ScopeCondition>,
) -> Result<R, ApiError> {
    let Some(scope) = scope else {
        return R::create(db, data).await;
    };
    let txn = db.begin().await?;
    let result = R::create(&txn, data).await?;
    check_result::<R, _>(&txn, std::slice::from_ref(&result), scope).await?;
    txn.commit().await?;
    Ok(result)
}

/// Run `create_many` with optional row confinement, preserving the resource's hooks.
///
/// # Errors
/// Returns the operation error, or refuses a row outside the scope.
pub async fn create_many<R: CRUDResource, C: ConnectionTrait + TransactionTrait>(
    db: &C,
    data: Vec<R::CreateModel>,
    scope: Option<&ScopeCondition>,
) -> Result<Vec<R>, ApiError> {
    let Some(scope) = scope else {
        return R::create_many(db, data).await;
    };
    let txn = db.begin().await?;
    let result = R::create_many(&txn, data).await?;
    check_result::<R, _>(&txn, &result, scope).await?;
    txn.commit().await?;
    Ok(result)
}

/// Run `update` with optional row confinement, preserving the resource's hooks.
///
/// # Errors
/// Returns the operation error, or refuses a row outside the scope.
pub async fn update<R: CRUDResource, C: ConnectionTrait + TransactionTrait>(
    db: &C,
    id: PrimaryKeyType<R>,
    data: R::UpdateModel,
    scope: Option<&ScopeCondition>,
) -> Result<R, ApiError> {
    let Some(scope) = scope else {
        return R::update(db, id, data).await;
    };
    let txn = db.begin().await?;
    check_existing::<R, _>(&txn, std::slice::from_ref(&id), scope).await?;
    let result = R::update(&txn, id, data).await?;
    check_result::<R, _>(&txn, std::slice::from_ref(&result), scope).await?;
    txn.commit().await?;
    Ok(result)
}

/// Run `update_many` with optional row confinement, preserving the resource's hooks.
///
/// # Errors
/// Returns the operation error, or refuses a row outside the scope.
pub async fn update_many<R: CRUDResource, C: ConnectionTrait + TransactionTrait>(
    db: &C,
    data: Vec<(PrimaryKeyType<R>, R::UpdateModel)>,
    scope: Option<&ScopeCondition>,
) -> Result<Vec<R>, ApiError> {
    let Some(scope) = scope else {
        return R::update_many(db, data).await;
    };
    let txn = db.begin().await?;
    check_existing::<R, _>(
        &txn,
        &data.iter().map(|(id, _)| id.clone()).collect::<Vec<_>>(),
        scope,
    )
    .await?;
    let result = R::update_many(&txn, data).await?;
    check_result::<R, _>(&txn, &result, scope).await?;
    txn.commit().await?;
    Ok(result)
}

/// Run `delete` with optional row confinement, preserving the resource's hooks.
///
/// # Errors
/// Returns the operation error, or refuses a row outside the scope.
pub async fn delete<R: CRUDResource, C: ConnectionTrait + TransactionTrait>(
    db: &C,
    id: PrimaryKeyType<R>,
    scope: Option<&ScopeCondition>,
) -> Result<PrimaryKeyType<R>, ApiError> {
    let Some(scope) = scope else {
        return R::delete(db, id).await;
    };
    let txn = db.begin().await?;
    check_existing::<R, _>(&txn, std::slice::from_ref(&id), scope).await?;
    let result = R::delete(&txn, id).await?;
    txn.commit().await?;
    Ok(result)
}

/// Run `delete_many` with optional row confinement, preserving the resource's hooks.
///
/// # Errors
/// Returns the operation error, or refuses a row outside the scope.
pub async fn delete_many<R: CRUDResource, C: ConnectionTrait + TransactionTrait>(
    db: &C,
    ids: Vec<PrimaryKeyType<R>>,
    scope: Option<&ScopeCondition>,
) -> Result<Vec<PrimaryKeyType<R>>, ApiError> {
    let Some(scope) = scope else {
        return R::delete_many(db, ids).await;
    };
    let txn = db.begin().await?;
    check_existing::<R, _>(&txn, &ids, scope).await?;
    let result = R::delete_many(&txn, ids).await?;
    txn.commit().await?;
    Ok(result)
}
